### ISSUE TITLE
Changelog generation failing

### ISSUE THREAD

**Issue by ToMe25** [srepollock/changelog-generator-action#5]
I tried to get this changelog generator to work with my [Java Library](https://github.com/ToMe25/ToMe25s-Java-Utilities), and after it originally didn't work, i added
```yml
      with:
        fetch-depth: 0
```
to my checkout job, after which this error occured while running the action:
```
 Traceback (most recent call last):
  File "/changelog_generator.py", line 46, in <module>
    main()
  File "/changelog_generator.py", line 42, in main
    commits = get_commit_log()
  File "/changelog_generator.py", line 10, in get_commit_log
    output = output.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5962: ordinal not in range(128)
```
which apparently tells me i used some character that this action can't handle, but i don't think i can change that.

**Comment by ToMe25** [comment]
Thanks :)
